version: 2
updates:
- package-ecosystem: docker
  directory: "/dev/base"
  schedule:
    interval: daily
  labels:
  - "automerge"
- package-ecosystem: docker
  directory: "/dev/java"
  schedule:
    interval: daily
  labels:
  - "automerge"
- package-ecosystem: docker
  directory: "/dev/nodejs"
  schedule:
    interval: daily
  labels:
  - "automerge"
