FROM robertsmieja/dev-base:latest

# For puppeteer
# RUN apk add --no-cache \
#     ffmpeg \
#     chromium \
#     ttf-freefont \
#     ca-certificates

# For node-gyp
# RUN apk add --no-cache --virtual build-dependencies \
#    python \
#    build-base

# Node
RUN apk add --no-cache \
    nodejs=12.17.0-r0 \
    npm=12.17.0-r0
