FROM robertsmieja/dev-base:latest

# JDK
RUN apk add --no-cache \
    openjdk11-jre-headless=11.0.7_p10-r1 \
    openjdk11=11.0.7_p10-r1 \
    openjdk11-jmods=11.0.7_p10-r1 \
    openjdk11-doc=11.0.7_p10-r1 \
    openjdk11-jdk=11.0.7_p10-r1 \
    openjdk11-src=11.0.7_p10-r1
