# hadolint ignore=DL3007
FROM robertsmieja/dev-base:latest

# JDK
RUN apk add --no-cache \
    openjdk11-jre-headless \
    openjdk11 \
    openjdk11-jmods \
    openjdk11-doc1 \
    openjdk11-jdk \
    openjdk11-src
